### ISSUE TITLE
package.json specify wrong files for bundlers.

### ISSUE THREAD

**Issue by thislight** [wobsoriano/solid-supabase#1]
`package.json` specify `exports.import` as "./dist/index.mjs", but it doesn't appeared in the directory. That will cause webpack use non-exists file and complain `Module not found: can't resolve "solid-resolve"`. 
Looks like the mjs version is generated under the name "./dist/index.js" and the cjs version is under "./dist/index.cjs". A workaround to this in `package.json`:
````diff
 "exports": {
-    "require": "./dist/index.js",
+    "require": "./dist/index.cjs",
-    "import": "./dist/index.mjs",
+    "import": "./dist/index.js"
   },
````

**Comment by wobsoriano** [comment]
Thank you!

https://github.com/wobsoriano/solid-supabase/commit/3bf4af8d0d23b78fd32bcd5fc281bada9fb09d68
