### ISSUE TITLE
Solid.js 1.4 removes default `children` from props.

### ISSUE THREAD

**Issue by thislight** [wobsoriano/solid-supabase#2]
Hello, I recognize solid.js 1.4 remove default `children` from Component: https://github.com/solidjs/solid/blame/6bf31e2167beeb1c17fca3762cdfd82b3ee8b1e0/packages/solid/src/render/component.ts#L22 .

Maybe the code requires minor change to work with solid.js 1.4
https://github.com/wobsoriano/solid-supabase/blob/7b1c19ac3a3b9dd5337e09b123cac4ebc68ff4d5/src/SupabaseProvider.tsx#L7

**Comment by thislight** [comment]
Hello, I made a simple PR for this: #3 .

**Comment by wobsoriano** [comment]
Fixed https://github.com/wobsoriano/solid-supabase/commit/44a4f50b9f3bb01b63566c222edd403d4a274dfa
