### ISSUE TITLE
Whats the path to updating all of the outdated dependencies

### ISSUE THREAD

**Issue by prodkt** [wobsoriano/solid-supabase#4]
Thank you for the starter template.

Given we are starting from scratch we'd at least like to try and make sure everything is up to date as possible. Is there an upgrade path? Or are these versions of dependencies needing to stay this way for compatibility?

**Comment by prodkt** [comment]
We went ahead and manually updated all the outdated dependencies one by one, for the most part no issues.

**Comment by wobsoriano** [comment]
Yeah, you should not have any issues. It expects solid >= 1.3.0 and that's about it
