### ISSUE TITLE
createOnAuthStateChange - session is not a function error

### ISSUE THREAD

**Issue by jonjojr** [wobsoriano/solid-supabase#5]
I keep getting an error when using the primitive createOnAuthStateChange 

auth.session is not a function

inside the primitives there is https://github.com/wobsoriano/solid-supabase/blob/master/src/primitives.ts

```
createRenderEffect(() => {
    if (client.auth.session())
      callback('SIGNED_IN', client.auth.session())

    onCleanup(() => {
      authListener?.unsubscribe()
    })
  })
}
```
if(client.auth.session()) <-- should this line use client.auth.session instead? and below line callback use client.auth.getSession()?

**Comment by wobsoriano** [comment]
What's your supabase version?

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/solid-supabase/releases/tag/v0.3.0
